language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run-script build
- npm run-script test
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: U06AzCM0X+WpPgLoR/Ngr572P9p6nIkvR/5GJXqUBsOnSyGCkmIcjZH9PrDmJb87oVmPWQGrJGa+ivoILTbx2usKrqXzIvOd3enxkQUjCjTiLf7ZkwTNspcFbqKPkF7S1sKTzZF+C8e325zocJUuhlMXnXRth7TrRUKQbgguX99+sBudmF2KLFPI/Y+1D8z/Trip5ab42XhiDZISxHBEqRq+H78nQa6wJzjlQlK/g9DeVlLkD/128VfWrKFDInnpiAetxrgaytgdLLGwOMo/ugY2Xnoess1cVLbFGDLt5eXj7MXfRhAVJBylboX7I4dB0JfPho6uZzkc1eXvaAHkIl3LZ41aSoJGKL5Sj2/6MtbyRiLkD2vfFceQzRJvr0xRQ7LTxYMfXKi/rn8GHIWzjMLI60v5nwgktE6hqGjKND1rdo4nxPCBjQ9kU8bExYYEbfGlf4AqyLe8vKNFqgTUChoCzAIwZnsYHeHuPn7Aug3JiWUJoYyhWhIsxL6Hly/NwQbQMhOGEEfw+QwKNgYf2SuzOHaUin/QJvO9JNJ1BCyOoR2xrak3SDBk/RIH6zq6o2gsWa1Ax3CiO36kWPiOzArVWInUszkAOC+uXwksXYWIOi1moXjglCW8ZMsUNszpKBBBMNMgGaDrRE6e4MxYSjiZn5557BqCV31/xaLL3pw=
  on:
    branch: master
notifications:
  slack:
    secure: RvaxJY/sKUlHj8F4vazDjcUrUItXEZhz2XAABFUqkfaK9d9wTincfLgqdBzZFndKoCDYajHdWWYCs1dhRCSwgZ6K5Co6wJKWYY6iC67YW0NOmO2m5MHLt9OQgbfGaD5gTKdlJblII2RGxzskkWsMR1IEypMKCm5IkgWmHeaK/0LXs36p+8VGgkBY3Rehd55T0IjkBXqJ+jFJmH9n149tT+BHnYjTeIWC3W+Us+2ydnYljmhXovFwz8MuXMD+GWnOtXOFrbVxX1XPc7mZJnTH6X/8fzbZZbnAsUPhAxN1kLk4jrUTAKkGdUuqlr81xUe0vHrML0JYjwhPirHu4AipIJ1U6l9GmcG/sd9LlPbUxuQkBygv39gcVHDAIAbEO6s8gOB22J2yENWINJfHNnEq0Ncd4vavI8VdAC+TRs8UkU1sPRDjwgI54rsf3oo/IqRdj7x+nERFaoKF6Q6LJ0BzoLzYu/19AveR2D25zLWDCPV4JH7y12FW0wqr8cPd+RQ0o13Atyqy3q0lAlJ5Ey+hDQAH/Qj7Lr7BQ3TODBYnwz3cD/hW8nUzXbDIo0knHBHBltsmhrvOHJC2z/OmOyf/QkQBblxv6PRFYuSjsg9P7HumfEf8Vh2nAAEu1yLdTOFwAX7Os/Sty5hQLAqjyi/lUxKDlW0h2ZFJI0BjnTuMPMw=
