language: node_js
node_js:
  - "6"
install:
- npm install
script:
- npm run-script build
deploy:
  provider: npm
  email: rafalnowosielski@me.com
  api_key:
    secure: "z9s7FLNi4BEz/oTAHwBk572xd4Pm1ZPK0wKTJT6O7Y/YAVDo+WjStVsouE9bcPzB0yXi7BStSH7lu9iGkVG4XnXB8D/V8AGwP5xk/0Tuv1grAKRndLcPjyc3SbN7QyABHh7+rdBzizFxr8Ps54h0F04sDMG7wewfAa7G4Jv+bQtV4MdrccwYS5Enyssd+KR4MLJdhdh5afj6ENyEG8aZ3tD+qurd+FZTNwO6vifQaLoL5uX2UjO/RDQJEla5bwGKseJwJxkls1AnSfEzb6gLF0hErppAauvFYzgDtUdon/2KocDAaE0fKrx0ZKGDo+l3VUo0TXnngxTv85JhRV4kz6lrQuTUn2O9aNmfQtyaxfWf2jxxrYCNKTUySsZRC24tr9QnJudKUxJ5pGUl+B2dTvYgaFzIe6s08VR85HN0ZRHFsMJAMpzjD3UULxBBgVB851Gp/iPi7SPuxvmudpNlLDXDaLmM88ClHDNHqG8UWI87FvlO+zwFn02udqafBhMX1q8wwTuWyIc4Ryt3HIN86Qqkt4VYwZVUssu9olwYD9wubYEy+naY/n7eMxqhzi6S0Ne3YNI6O/XWt9r0RGVbEq+ipxi3pUMtJzteA+avFGgZX1Q05CIfyyFltMzMHvSyHqOFTVCTqyffoxrD4E7foN1aWwdISQNdWlUKFwxVCVg="
  on:
    branch: master
notifications:
  slack:
    secure: "X8/oTE7J9+0qSxo6SRbBHqNNRevOUUBOaKAkUC0rQJorSv3bF7p8jPsU4mo+Ct+/WI2jfEaubVFBiCWqL9GKsd6sZzmAI9lZRcF4naO2EvOxlzhX/I1pgWMean2on0xqqwAWBjWAEqbovtswj18K4+tKvZpkHxaOAdam8mKUnZBd5SxjKIjgettnFiTX7XaoZqRjHh2cUNHpKxiLL88IFZa8Ksye0ZaeqRqxsUXs9mwczc17ta9tslHk2xqRwnRzKB7Y6R5eEnIsGu5ufdIINsM0eMB5dBzkhHYxJ5hqWf+wR7CxUQjRuOe5dyWayNXEqPFhgQPH68X0jQ7Pn8WeE0puthDWef4T4tmk2vZBaRukBfL7/MsMBsJD5xAQjZ0q8luwTazC4cMKmb5DIJujh6W8D7q+L+Yr25MVYmc1rlWxWGccO1jeJ5uX0TNEiQx3JIGNjcRa9n40Zp3Gm/6+njrCx4DhsPvzyFBr9A0O63XOJ+RMNcF43tV25nS/hLTsnFyE27HqJJLnSKbpES/UFr5XcJWuWedWL09PE1wwgGphMLJRvijoBYnjmPgIY4D8EXRejW+1ubANPnKuLoPFaNUvSX4V8TAbBo5y3vE13piyElYXhYPPetIbshLCucauBYSE4S2i7JHB+wrc/4JPcWOX6p0xnGY2TrgaPiK6XoQ="
