language: node_js
node_js:
  - "6"
install:
- npm install
script:
- npm run-script build
deploy:
  provider: npm
  email: rafalnowosielski@me.com
  api_key:
    secure: z9s7FLNi4BEz/oTAHwBk572xd4Pm1ZPK0wKTJT6O7Y/YAVDo+WjStVsouE9bcPzB0yXi7BStSH7lu9iGkVG4XnXB8D/V8AGwP5xk/0Tuv1grAKRndLcPjyc3SbN7QyABHh7+rdBzizFxr8Ps54h0F04sDMG7wewfAa7G4Jv+bQtV4MdrccwYS5Enyssd+KR4MLJdhdh5afj6ENyEG8aZ3tD+qurd+FZTNwO6vifQaLoL5uX2UjO/RDQJEla5bwGKseJwJxkls1AnSfEzb6gLF0hErppAauvFYzgDtUdon/2KocDAaE0fKrx0ZKGDo+l3VUo0TXnngxTv85JhRV4kz6lrQuTUn2O9aNmfQtyaxfWf2jxxrYCNKTUySsZRC24tr9QnJudKUxJ5pGUl+B2dTvYgaFzIe6s08VR85HN0ZRHFsMJAMpzjD3UULxBBgVB851Gp/iPi7SPuxvmudpNlLDXDaLmM88ClHDNHqG8UWI87FvlO+zwFn02udqafBhMX1q8wwTuWyIc4Ryt3HIN86Qqkt4VYwZVUssu9olwYD9wubYEy+naY/n7eMxqhzi6S0Ne3YNI6O/XWt9r0RGVbEq+ipxi3pUMtJzteA+avFGgZX1Q05CIfyyFltMzMHvSyHqOFTVCTqyffoxrD4E7foN1aWwdISQNdWlUKFwxVCVg=
  on:
    branch: master
notifications:
  slack:
    secure: pc3HjrJRFUaTlpxvHL5azVglO1WbYKc6FTuzronJlSyW5Mo+6X5u96zrvhuEXG9WClsQ4wyumluCuJy93XRJw/Icgc35AZykJpfHBvVoDOM2M4U9HaTheepiqJaxtR/t/b7A6pPUNfbqu8qic5AluXmDVT6bda6Njy+i1vDS+/Wr5wRp99V7FDZFFpFsEOiQ/dswmIdvibQC7jy6FZYsWtIE1se+Lc+nc8x47jcqp3C+W3i1GM3NW5aTEJnLfKn8RbKfXA+EnpL31ZSLqoINwyaCZjAZCLx6ACN+sIrPpu+ABGXYpgsD/0yq0f/3xcORRLEZNmG9YfZyYV19xXx3zBIZwpYP14wr/QIdPmrKw9aXOwy4gQGs75D1v74EKEnN3lL8etiR1AktK2P3Bwd1HPwwpOFSw2MsEL9gRtykf1O0l0vxzdk+s8SRQLhuUAOwe6IZzbjj+2oBO4nqqRUklvwwFJs6R3VwvNeN+fYBeM0r0MjsvnHXGR8iPhDgIc1H5qDiFaxLkuBF7rgKeiWR5mUtnKKpp/1Klt8MQEfZL7peL283BCOS2P/HaJgK/9yRaBt3PRlOM22doK6qKgQY5mNLmcKqf4OiqhOu/jI6aQhnQdnzlskXBBEhi3nFbBZCYyXxrUg8lWGt+BPtAXvZ7WWjUP/J/ElBOKAaBJ0YUYM=
