language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run-script build
- npm run-script test
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: 75ow4yrTmtsJkQPom2q+Bi+LZgK0YAgVtsA3vJwtrd971RL5fobYoVKTBCcksIfM7uUw7dBPZUxDlpQpJ/jNqS1/wONlZKngkYpjSpZKfZ59sYazIeJ7Yi+EOehVqd4TZqsL/dT+wFd15zKBQA1b2y76Si3BYCohMS3icAkrA4yVQAkssN7hZip78CbZ2bhPDDrgXOvF0VsYriahHSqHkBAAUguRTPuacHHtYbzwm2vgPoZORH4Jxy3Px133cqj1q0RcfKYVEplgkj83twm7qwlMLUboU+0Bvf6PpEzWXZ3yImKHnXhhCZVHuBqcrCUOxNPPxOnnTgowf27MuskRbqRmjQp7LnSVp3qfxy39FLsgaDkyMRvDW5n4TQqZkWMZH3AwWsQKEEQXAiVRF/GDc8oi4ZPSrnVIdfelsH+103XJYcNHijF3d7hXWGxZbPYt+WFYOujMhiR+AxUID4cDXEAPuCf/OD3437TE4UQJxzYDjXt7EAr1ZuL1JSMjASVcccW+/jehRFDRwpjfsfSKFYGK54gC/a3gWUHCPbJfckcb4lk8QsuVsQ+ucOXBEoa/rQ+tK0gawUnAIXJ++W1htC+6cQm1WiX3+QNLMUllmIT20UVZBc2xMpJvgmGg27M4fNX0fKMne6ek9DvmO2QC6jx5jZOzvzuFVuelMNWzDDs=
  on:
    branch: master
notifications:
  slack:
    secure: RvaxJY/sKUlHj8F4vazDjcUrUItXEZhz2XAABFUqkfaK9d9wTincfLgqdBzZFndKoCDYajHdWWYCs1dhRCSwgZ6K5Co6wJKWYY6iC67YW0NOmO2m5MHLt9OQgbfGaD5gTKdlJblII2RGxzskkWsMR1IEypMKCm5IkgWmHeaK/0LXs36p+8VGgkBY3Rehd55T0IjkBXqJ+jFJmH9n149tT+BHnYjTeIWC3W+Us+2ydnYljmhXovFwz8MuXMD+GWnOtXOFrbVxX1XPc7mZJnTH6X/8fzbZZbnAsUPhAxN1kLk4jrUTAKkGdUuqlr81xUe0vHrML0JYjwhPirHu4AipIJ1U6l9GmcG/sd9LlPbUxuQkBygv39gcVHDAIAbEO6s8gOB22J2yENWINJfHNnEq0Ncd4vavI8VdAC+TRs8UkU1sPRDjwgI54rsf3oo/IqRdj7x+nERFaoKF6Q6LJ0BzoLzYu/19AveR2D25zLWDCPV4JH7y12FW0wqr8cPd+RQ0o13Atyqy3q0lAlJ5Ey+hDQAH/Qj7Lr7BQ3TODBYnwz3cD/hW8nUzXbDIo0knHBHBltsmhrvOHJC2z/OmOyf/QkQBblxv6PRFYuSjsg9P7HumfEf8Vh2nAAEu1yLdTOFwAX7Os/Sty5hQLAqjyi/lUxKDlW0h2ZFJI0BjnTuMPMw=
